### PR TITLE
support for gpu and intel mic resources

### PR DESCRIPTION
**Pull request by sartiran**
Minimal setup for supporting gpu and intel mic resources. Tested with grid submission with Marco Verlato and Lisa Zangrando.

### CODE REVIEW

**Comment by jrha** [comment]
LGTM, but then we don't have any MIC resources...

**Comment by sartiran** [comment]
Hi James,
I don't get what do you mean? is there something else that I should add to make things more complete?
Cheers,
a.

**Comment by jrha** [comment]
Sorry! No it looks fine, but we don't run GPUs or MICs at RAL, so I can't be sure that I have thought about it properly!

**Comment by jrha** [comment]
@alahiff?

**Pull request merged**
