### PR TITLE
new offline/draining mechanism for condor nodes

### PR DESCRIPTION
**Pull request by sartiran**
Just a small change in the way draining and offline nodes are managed. In prod at GRIF_LLR

### CODE REVIEW

**Comment by jrha** [comment]
Could you copy the script part into a seperate file and load it with `file_contents()` please? It makes things so much tidier.

@alahiff - any comments?

**Comment by sartiran** [comment]
done (if I got correctly your suggestion). I do not completely agree with the idea to disperse,  just for the sake of having clean template, the information that has to go on the same htcondor config file. I'd probably rather split in two files on the htcondor level. But for the moment it is fine like this, at least on my side.

**Comment by jrha** [comment]
Thanks! I guess it's a personally thing but I find it very difficult to follow logic built into EOF blocks, this is something that would probably be well suited to a dedicated template (TT) for metaconfig.

**Comment by sartiran** [comment]
Yep. I share with you the difficulties with EOF blocks. On the long term metaconfig is probably the way to go...

**Comment by alahiff** [comment]
@jrha no comments from me, looks fine.

**Pull request merged**
