### PR TITLE
DPM Storage Accounting

### PR DESCRIPTION
**Pull request by Pansanel**
This set of templates permits to configure the DPM Storage Accounting needed by EGI, as described on:
https://wiki.egi.eu/wiki/APEL/Storage

### CODE REVIEW

**Comment by jrha** [comment]
@Pansanel my understanding is that recent versions should install `star-accounting.py` as `/usr/share/lcgdm/scripts/star-accounting.py` so you shouldn't need to be shipping the script as part of the configuration (which always seems like a bad idea to me anyway).

**Comment by jrha** [comment]
The correct version of the script seems to have been present in `dpm-server-mysql-1.8.11-1.el7.x86_64.rpm` and later versions.

**Comment by Pansanel** [comment]
The scripts in dpm-server-mysql-1.9.0-1.el6.x86_64 is version 1.0.4. The required version is 1.2.4. So, we still need to push the right version with Quattor.

**Comment by jrha** [comment]
Ok, seems like it would be worth reporting the bug upstream though.

**Comment by Pansanel** [comment]
So can I merge?

**Pull request merged**
