### PR TITLE
Ensure all files are unix format and strip trailing whitespace

### PR DESCRIPTION
**Pull request by jrha**
White-space only changes, review with `?w=1`!

### CODE REVIEW

**Comment by jrha** [comment]
I might add a line-ending check to panlint.

**Comment by stdweird** [comment]
@jrha do you intend to fix the indentation issues?

**Comment by jrha** [comment]
Noooooooooo

**Comment by stdweird** [comment]
@jrha so i just merge current state?

**Comment by jrha** [comment]
Sure!

**Pull request merged**
