### PR TITLE
fix pbs static ldif paths when GIP_CE_USE_CACHE is true

### LINKED ISSUE #135: Problem with publication information by BDII-Local
I got a alert on   

`midmon.egi.eu`

on my bdii about information the bdii publish
```
CRITICAL - errors 78, warnings 26, info 52
Summary per type of error, warning and info message:
E022 - Default value published (GLUE2ComputingShareWaitingJobs): 26
E023 - Default value published (GLUE2ComputingShareEstimatedAverageWaitingTime): 26
E024 - Default value published (GLUE2ComputingShareEstimatedWorstWaitingTime): 26
I046 - Number of seconds higher than 1 million (GLUE2ComputingShareEstimatedAverageWaitingTime): 26
I047 - Number of seconds higher than 1 million (GLUE2ComputingShareEstimatedWorstWaitingTime): 26
W025 - Incoherent number of total jobs (GLUE2ComputingShareTotalJobs): 26
```

### PR DESCRIPTION
**Pull request by pigay**
Fixes #135

### CODE REVIEW

**Comment by jouvin** [comment]
I am reluctant to accept this fix. See comment in #135.

**Comment by pigay** [comment]
I don't understand your hesitation.

It remains that the config file refers to a file which is not configured by quattor. I couldn't find any piece of a template where the symlinks are create. This must have disappeared from the repo at some point.

The people involved into upgrading to the new `lcg-info-dynamic-scheduler` will probably have to refactor the `gip/ce/pan` template, so it doesn't harm to accept this fix.

Anyway. Feel free to reject this PR. I just intended to contribute a bit.

**Comment by jouvin** [comment]
@pigay read the GGUS ticket, it explains why this file should be outside of the standard location. The real fix would probably be the other way around: ensure that the file is created in the right location. Because of the bug in the GGUS ticket, it was temporarily created in the only location where it could be found by the buggy version of `lcg-info-dynamic-scheduler`. Now that the pb is fixed and the config file taken into account, I think we should create it at the right place rather than amend the config file (your PR). I hope to find the time to work on it this afternoon...

**Comment by jouvin** [comment]
Except if you want to do it!

**Comment by pigay** [comment]
@jouvin I had missed the GGUS part indeed and didn't understand your comment on #135.

I'd be very happy to try to help if I could. But I'm even unable to guess how these static files are generated.

**Comment by jouvin** [comment]
I started working on it... In fact, as I was remembering, I left FIXME lines explaining what had to be done so should not be too difficult... More later!

**Comment by jouvin** [comment]
As explained, this workaround is not the right fix... Replaced by #141.

**Comment by jouvin** [comment]
As said in #141, let's merge this one into 15.4 as a temporary workaround until the filxed `dynsched-generic` is really released (end of May), giving time for more testing and clearing the last issues reported by @pigay in #141 discussion.

**Pull request merged**
