### PR TITLE
Add the list of VOMS server for VO Fermilab

### PR DESCRIPTION
**Pull request by jose-caballero**
Add support for VO Fermilab

### CODE REVIEW

**Comment by Pansanel** [comment]
Hi,

VOMS server should now be managed by `https://github.com/quattor/tools/tree/master/grid/update-vo-config`.

**Comment by jrha** [comment]
@Pansanel in that case we should remove the templates from this repo?

**Comment by jrha** [comment]
It might be also worth noting that there isn't a proper VO card for this VO.

**Comment by jouvin** [comment]
For both reasons mentioned, I close this PR. @jose-caballero please note that you can always override at a site level something provided in the template library if you want to use something not "standard" like a site-specific account prefix or base UID. You just need to create a template `vo/site/fermilab.pan` (the name must be the same as the base one) and define the properties you want to override.

**Pull request closed without merging**
