### PR TITLE
GIP CE: fix for problem introduced by workaround for a buggy lcg-info-dynamic-scheduler

### PR DESCRIPTION
**Pull request by jouvin**
See #135 for details.

Replacement for #137.

### CODE REVIEW

**Comment by jouvin** [comment]
Would be good if @pigay or @jas01 could test before merging... but would also be nice to have it in 15.4!

**Comment by pigay** [comment]
I gave a try. I'm too stupid to understand what you've done.

I see in `/etc/bdii/gip/lcg-info-dynamic-scheduler-pbs.conf`:
```
[Main]
static_ldif_file: /var/glite/static-file-all-CE-pbs.ldif
static_glue2_ldif_file_computingshare: /var/glite/static-file-all-CE-pbs-glue2.ldif
...
```

I'm confused with `static_glue2_ldif_file_computingshare`. I thought it was something like `/var/glite/ComputingShare.ldif` before.

However, on my CE, this file `/var/glite/static-file-all-CE-pbs-glue2.ldif` was created but is empty.

Strangely, glue-validator seems to be happy:
```
$ glue-validator -H ce0.bordeaux.inra.fr -p 2170 -b o=glue -k -v 1 egi-profile
OK - errors 0, warnings 0, info 0 | errors=0;warnings=0;info=0
```

**Comment by jouvin** [comment]
I cannot believe your are too stupid to understand!!! In fact I was lazy and I just deleted every line preceded by a FIXME saying it should be deleted when the bug was fixed! (it's true that I added a commit this morning which is just about reformatting, take the previous one if you want to see the real difference).

`/var/glite/static-file-all-CE-pbs-glue2.ldif` should be removed normally. But as there is no easy way to ensure that a file doesn't exist (or remove it), we ensure that the file is empty (which is harmless).

Thanks for the (positive) feedback.

**Comment by jouvin** [comment]
PR closed by mistake...

**Comment by pigay** [comment]
I'm puzzled with the following: @jas01 and I had a problem because of missing files (for me: `/var/glite/ComputingShare.ldif`). We had to make a link by hand (or my proposed fix: to point to the real location of this file) to make it work.

Your fix creates an empty file in this location and it's ok...

Never mind, if it works...

**Comment by jouvin** [comment]
Thanks for pointing out that I may have missed something... Clearly the configuration of `lcg-info-dynamc-scheduler-pbs` still refers to the LDIF file in `/var/glite`  for GLUE2 and I agree with you that seems to be a mistake. At least the empty file is not correct. I will check but I don't think there is any reason to use a file outside the standard location for GLUE2. In this case, I'll fix the path in the conf file for GLUE2 (`static_glue2_ldif_file_computingshare`).
More later...

**Comment by jrha** [comment]
@jouvin you will need to rebase this for 15.6.

**Comment by stdweird** [comment]
@jouvin this is not mergeable. maybe a rebase?

**Comment by jrha** [comment]
@jouvin any chance of rebasing this during the workshop?

**Comment by jouvin** [comment]
I'll have a look...

**Comment by stdweird** [comment]
@jouvin ping

**Comment by jouvin** [comment]
Overwhelmed, sorry... I'll try tonight or tomorrow.

**Comment by jouvin** [comment]
I had a look at this pending PR. It is at least in a mergeable state... but I don't really remember all the details from the discussion and I need to test that it does the appropriate thing.... I tend to think it is ok but I'll try to test it by tomorrow evening. Not sure I can promise it for today...

**Comment by jrha** [comment]
Giving this to @guillaume-philippon to review as I really don't understand the code.

**Comment by jrha** [comment]
@Pansanel do you have time to look at this? I'm not going delay 15.8.0 for it, but it would be good to get it merged.

**Comment by jouvin** [comment]
I was in charge in fact but faced a difficulty because it diverged too much from what we are using... It would probably be better to use the last version used at LAL as a basis, as it brings/fixes the HTCondor support, but this would require @guillaume-philippon to confirm it is a drop-in replacement...

**Comment by jrha** [comment]
@guillaume-philippon can this be merged?

**Comment by jouvin** [comment]
No, this PR should not be merged as it is. My last comment was to ask @guillaume-philippon if we could just drop the version used at LAL as a replacement of the version currently in the PR...

**Comment by jouvin** [comment]
I'm closing this PR that is too old to be merged, as the code changed a lot to add the HTCondor support. I don't think that the original problem is fixed but we need to restart from the current GIP CE version (see #162).

**Pull request closed without merging**
